### PR TITLE
Add CircleCI config

### PR DESCRIPTION
**Pull request by annekainicUSDS**
Addresses #23.

I didn't include deploy instructions because I'm not sure what deployment process users of this repo will want, and it be different from user to user. Do you think we should include something generic that someone could edit in their forked version, or not include anything at all? @dmethvin-gov

### CODE REVIEW

**Comment by dmethvin-gov** [comment]
I am not sure what our plan should be long term. Now we have a CircleCI setup which will be forked so we'll have to figure what happens when users do that.

**Comment by annekainicUSDS** [comment]
I wasn't able to try it on my local branch because I wasn't able to install the circleci CLI tool because I don't have admin on my computer, which is needed to install it. I'm submitting a request to IT for help in downloading this, but it might take some time to get a response. If you have a suggestion for another way I can test this without having to install anything that would be great!

**Comment by dmethvin-gov** [comment]
I didn't install the CLI tool either, I just used their website to configure my own fork to run CI. I'm not sure what more the CLI does?

**Comment by annekainicUSDS** [comment]
Ah okay, that's helpful. The CLI tool was just what was recommended to test this locally in the CircleCI docs, so that's what I tried first! Perhaps its useful to for testing local branches instead of pushed branches to GitHub?

**Comment by annekainicUSDS** [comment]
Okay! Was able to fork this repo and run CI on my forked version and the build passed! https://circleci.com/gh/annekainicUSDS/us-forms-system-starter-app/2

**Comment by dmethvin-gov** [comment]
The first time? I am super jealous!

**Comment by annekainicUSDS** [comment]
@dmethvin-gov well I copied the config mainly from USFS so I think you did the hard leg work on that :)

**Pull request merged**
